// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDraY7bI4tX_9LIOXhjO4CJGFXWw7nunyg',
    appId: '1:24358261776:web:9b72db273bee389dd86695',
    messagingSenderId: '24358261776',
    projectId: 'ieee-sst',
    authDomain: 'ieee-sst.firebaseapp.com',
    storageBucket: 'ieee-sst.appspot.com',
    measurementId: 'G-2PCLG76BYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo26LBS3_1KJnhRk2fvM7E8GSHHCzAi5o',
    appId: '1:24358261776:android:c16fdae64d03495dd86695',
    messagingSenderId: '24358261776',
    projectId: 'ieee-sst',
    storageBucket: 'ieee-sst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQotxi8AHLPEf-4N7kmqFOkqRUezGHF9k',
    appId: '1:24358261776:ios:19aa245bb5d5008fd86695',
    messagingSenderId: '24358261776',
    projectId: 'ieee-sst',
    storageBucket: 'ieee-sst.appspot.com',
    iosClientId: '24358261776-p285ju0o0vkf8qsshlj469f45htfnru4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeSst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQotxi8AHLPEf-4N7kmqFOkqRUezGHF9k',
    appId: '1:24358261776:ios:19aa245bb5d5008fd86695',
    messagingSenderId: '24358261776',
    projectId: 'ieee-sst',
    storageBucket: 'ieee-sst.appspot.com',
    iosClientId: '24358261776-p285ju0o0vkf8qsshlj469f45htfnru4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeSst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDraY7bI4tX_9LIOXhjO4CJGFXWw7nunyg',
    appId: '1:24358261776:web:a7c6909f32c23a16d86695',
    messagingSenderId: '24358261776',
    projectId: 'ieee-sst',
    authDomain: 'ieee-sst.firebaseapp.com',
    storageBucket: 'ieee-sst.appspot.com',
    measurementId: 'G-JPW281T5K5',
  );
}
